### ISSUE TITLE
Добавить ссылку на cifar-10 в инструкцию

### ISSUE THREAD

**Issue by diman8** [dyashuni/ITMM_DL_in_CV_2018#1]
Предлагаю добавить ссылку на CIFAR-10 в Установка.docx, т.к. не уверен, что все смогут разобраться shell-скрипте "Assignment1/cs231n/datasets/get_datasets.sh".

Например:
Скачать dataset CIFAR-10 (http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz).
Распаковать файлы из архива в корень "Assignment1/cs231n/datasets/".

**Comment by dyashuni** [comment]
Хорошая идея,
Спасибо, поправил.
